# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew Schafer
email: schafeandrew@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I’m a software developer with 6 years of industry experience. While the frameworks I use, the industries I support, and even role descriptions have varied, one thing has been consistent: I thrive delivering consumer-first digital products.
  I love starting with a user problem, then finding the best way to solve that through technology. Recently, I’ve been working with NextJS and React, as well as custom themes for WordPress using PHP and Advanced Custom Fields.
  My priorities in the work I deliver are fast, maintainable, modern, accessible, and fun. This is done through good design, smart development patterns, and as much as I don’t love this word: _strict_ scss standards.
  I will always push for the right tooling for the job to ensure we don’t overbuild, while leaving headroom for growth. I strive for an end result that is a beautiful, user friendly platform to engage with your community in new, thoughtful ways.
  When I’m not crushing user stories,  I can be found behind a camera wherever I found a cheap plane ticket, volunteering on my local Parks + Placemaking committee board, or trying to read too many books at once.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  schaferandrew
instagram_username: schafer.andrew
linkedin_username: andrew-schafer-617305107

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      types: "post"
    values:
      layout: "post"

show_excerpts: true

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
